apiVersion: apps/v1
kind: Deployment
metadata:
  name: sreagent-frontend
  namespace: sreagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sreagent-frontend
  template:
    metadata:
      labels:
        app: sreagent-frontend
    spec:
      containers:
      - name: sreagent-frontend
        image: kunyiliu1022/sreagent-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sreagent-frontend-external
  namespace: sreagent
spec:
  type: LoadBalancer
  selector:
    app: sreagent-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80